### ISSUE TITLE
helios return hex value with leading zero, and golang will report:json: cannot unmarshal hex number with leading zero digits into Go value of type *hexutil.Big

### ISSUE THREAD

**Issue by myfirst-crypto** [a16z/helios#112]
golang client make request getBalance:
{"jsonrpc":"2.0","id":1,"method":"eth_getBalance","params":["0x0143bd0cc24d0e1ea46353be5a7972f42abcb175","latest"]}

helios return:
{"jsonrpc":"2.0","result":"0x000000000000000000000000000000000000000000000000000824962cde342e","id":1}

then golang client panic with fatal error:
json: cannot unmarshal hex number with leading zero digits into Go value of type *hexutil.Big

I check others rpc endpoint will return:
{"jsonrpc":"2.0","result":"0x824962cde342e","id":1}

**Comment by ncitron** [comment]
Good catch! Will fix
