### ISSUE TITLE
error: could not compile `client`

### ISSUE THREAD

**Issue by upalchowdhury** [a16z/helios#128]
Steps taken : 
1. git clone git clone https://github.com/a16z/helios.git
2. cargo build

getting below error, 
===============

thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(0, None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), []), Binder(OutlivesPredicate(rpc::RpcInner, ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), [])], reveal: UserFacing, constness: NotConst }, value: Binder(TraitPredicate(<for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i> {std::future::ResumeTy, &'a mut execution::evm::Evm<'b, execution::rpc::http_rpc::HttpRpc>, &'c execution::types::CallOpts, &'d execution::evm::Evm<'e, execution::rpc::http_rpc::HttpRpc>, impl std::future::Future<Output = std::result::Result<std::collections::HashMap<ethers::types::H160, execution::types::Account>, execution::errors::EvmError>>, ()} as std::marker::Send>, polarity:Positive), []) } }
- dep-node: evaluate_obligation(a5bd18beafa14380-25b55d5386557813)', /rustc/42325c525b9d3885847a3f803abe53c562d289da/compiler/rustc_query_system/src/dep_graph/graph.rs:316:9

........
........

note: rustc 1.67.0-nightly (42325c525 2022-11-11) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i> {core::future::ResumeTy, &'a mut execution::evm::Evm<'b, execution::rpc::http_rpc::HttpRpc>, &'c execution::types::CallOpts, &'d execution::evm::Evm<'e, execution::rpc::http_rpc::HttpRpc>, impl core::future::future::Future<Output = core::result::Result<std::collections::hash::map::HashMap<primitive_types::H160, execution::types::Account>, execution::errors::EvmError>>, ()}: core::marker::Send`
#1 [typeck] type-checking `rpc::<impl at client/src/rpc.rs:112:1: 112:31>::estimate_gas`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `client`

**Comment by refcell** [comment]
Can't reproduce, try upgrading rust since your last nightly upgrade was `2022-11-11`. Run `rustup update` (or `rustup update nightly` to be specific)

**Comment by upalchowdhury** [comment]
updating to lates solved the issue thanks.

**Comment by upalchowdhury** [comment]
`rustup update nightly` resolved the issue. Thanks @refcell

**Comment by refcell** [comment]
Great! Glad that worked!

**Comment by ncitron** [comment]
Yeah this error was due to https://github.com/rust-lang/rust/issues/104238 which effected the nightly compiler for a little less than a week.
