### ISSUE TITLE
consider refactoring to leverage `ethereum-consensus`

### ISSUE THREAD

**Issue by ralexstokes** [a16z/helios#132]
some of the functionality I see in the repo, e.g. various chain config, a lot of the types under the `consensus` crate, or a definition like a `Bytes32`, are defined here:

https://github.com/ralexstokes/ethereum-consensus

I'd consider refactoring to leverage this crate to lower maintenance burden for this repo

If this issue gets sufficient engagement, I'm happy to open a PR for the refactoring

**Comment by ncitron** [comment]
I completely agree. I don't want to contribute to a bifurcation of eth consensus types, and it would be great to establish ethereum-types as a standard.

**Comment by ncitron** [comment]
Closing this as I don't think we want to do this for now. After considering I think we want to be able to have more control of the type system, and to add new methods on various types that are light client specific.
