### ISSUE TITLE
implement block tx count rpc methods

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#139]
Implement `eth_getBlockTransactionCountByHash` and `eth_getBlockTransactionCountByNumber`.

To implement this, I suggest looking at how `eth_getBlockByHash` and `eth_getBlockByNumber` are implemented. We should be able to service these requests without making any rpc requests, since the `ExecutionPayload` that we have already has a `transactions` field which we can check the length of.

**Comment by giovannivignone** [comment]
I can take eth_getBlockTransactionCountByHash

**Comment by giovannivignone** [comment]
@ncitron we can close this issue. I don't have access to do so

**Comment by ncitron** [comment]
closed by #142
