### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by eskimo** [a16z/helios#152]
Running with `helios --execution-rpc https://eth-mainnet.g.alchemy.com/v2/...` results in the following:

```
[2022-12-15T02:50:59Z INFO  client::rpc] rpc server started at 127.0.0.1:8545
Illegal instruction (core dumped)
```

**Comment by ncitron** [comment]
What operating system and platform are you using? I've seen this happen once before with someone running arch, and the solution was for them to build from source rather than use the prebuilt binary (which gets compiled on a ubuntu or osx machine and works with most systems).

**Comment by eskimo** [comment]
Ubuntu 20.04 64

**Comment by ncitron** [comment]
Hmmm that seems like a platform that should work which is strange.

Anyway, if you have rust installed, you can clone and cd into the repo and run `cargo build --package cli --release && rm ~/.helios/bin/helios && cp ./target/release/helios ~/.helios/bin`. This will build the package from the source and replace your current helios installation.

**Comment by eskimo** [comment]
Thanks this worked. 

Now I just need figure out what to do with this new error:
`Error: Checkpoint is too old. Please update your checkpoint. Alternatively, set an explicit checkpoint fallback service url with the `-f` flag or use the configured external fallback services with `-l` (NOT RECOMMENED). See https://github.com/a16z/helios#additional-options for more information.`
