### ISSUE TITLE
Fails with get_proof

### ISSUE THREAD

**Issue by anegg0** [a16z/helios#165]
Hi team,
Here is my env:

1. Helios version: latest
2. DevTool: Forge latest
3. Endpoint: ETH_RPC_URL=https://polygon-mumbai.g.alchemy.com/v2/<my_api_key_here>
4. Box: Linux, Pop!_OS 22.04 LTS

I can run helios, it synchronizes without an issue, but when I want to deploy a contract, this error is returned:
`(code: -32001, message: Custom error: rpc error on method: get_proof, message: Deserialization Error: invalid type: null, expected struct EIP1186ProofResponse at line 1 column 4. Response: null, data: None)`

The forge command I'm invoking is:
`forge create ./src/BleedToken.sol:BleedToken --mnemonic ../../passphrase --gas-limit $ETH_GAS_LIMIT --rpc-url http://127.0.0.1:8545`

I've tried switching to Goerli, with the same outcome.

The very same command runs well when interfacing directly with the Alchemy endpoint.

Any help would be appreciated.
Thanks!
Gael

**Comment by ncitron** [comment]
Helios does not support Polygon. Also if you want to use Goerli, you need to pass in `--network goerli` as a flag. If you use goerli you also need to supply a `--consensus-rpc`. For mainnet we supply one for you since they are hard to get a hold of.

**Comment by ncitron** [comment]
Hmmm it looks like nimbus has changed the light client data api recently which breaks helios when connected to a newer version of nimbus. Let me look into why it has changed and get this fixed up.

**Comment by anegg0** [comment]
My blind guess points to [this page](https://nimbus.guide/api.html). Not sure it helps.

**Comment by anegg0** [comment]
I noticed your [PR merge ](https://github.com/a16z/helios/pull/169), thank you. 
After running heliosup, I still get the same error. 
Do you consider the bug fixed?

**Comment by ncitron** [comment]
I haven't made a new release of helios yet so heliosup will not work yet. I have one more PR I want to merge first before cutting a new release, then heliosup should fix it. Will ping you here when it is ready.

**Comment by ncitron** [comment]
I've just pushed the update. Running `heliosup` should bring you to the latest version.

Make sure you use a consensus endpoint that is nimbus. The one you were using before (http://testing.prater.beacon-api.nimbus.team) should work. Let me know if this resolves your issue.

**Comment by anegg0** [comment]
Works just fine now, thanks much for fixing this so quickly!

**Comment by ncitron** [comment]
Awesome. Thanks for reporting the issue.
