### ISSUE TITLE
toolchain file specifies `nightly`, should specify a specific version of nightly

### ISSUE THREAD

**Issue by prestwich** [a16z/helios#178]
Specifying nightly uses the locally installed version of nightly, which may not have all necessary features. This also defeats the purpose of using a toolchain file, as users will compile using different versions from each other (the thing the toolchain file is intended to prevent). Instead, use a specific commit date, e.g. `nightly-2023-01-01`

It is also recommended that you document the supported rust version in the readme, so those of us with weird installs can compile more easily :)

E.g. Helios will not compile on versions without `map_first_last` feature, which was stabilized in rust 1.66.0 (which is only a month old!), and may not be present or active in earlier nightlies. Users who haven't updated their nightly in a month can't clone + compile without troubleshooting.

This could be a 1-line PR, but i didn't want to submit it without a discussion about it first 😅

**Comment by ncitron** [comment]
Thanks for pointing this out. This makes sense to me. Do you want to open a PR to add a reasonable nightly version? If not I can do so.
