### ISSUE TITLE
consider switching from `log` crate to `tracing`

### ISSUE THREAD

**Issue by prestwich** [a16z/helios#181]
Given that internal lib usage seems to be a goal of the project, `log` is an anti-feature. [tracing](https://docs.rs/tracing/latest/tracing/) should be used instead, to give consuming binaries better control over events. Tracing offers drop-in replacement macros for `log`, so integration should be smooth

**Comment by ncitron** [comment]
Thanks for sharing this crate! This is seems very useful, especially due to the async nature of Helios. Will definitely be switching over to this.

For libraries, is the idea that they can use subscribers and decide which of Helios's logs they want to ingest?

**Comment by prestwich** [comment]
generally speaking, 
- events are structured execution data with a message
- events may occur within spans, which contain execution context 
- libraries and binaries create spans and events
- binaries register 1 or more subscribers to handle events
    - subscribers may be filtered (envfilter, e.g.)
    - subscribers may output events & spans over the network (e.g. opentelemetry)
    - subscribers may output events & spans locally (to stdout or to files)

some best practices:
- use attributes, not string interpolation when emitting events `info!(my_prop = %something, "message")` not `info!("message {}", something)`
- be careful when using Debug/Display impls, as they may cause events to be overly verbose
- libraries should not register subscribers
- too many spans can make overly verbose events is just as bad as no spans
- when instrumenting tasks, instrument the async block, not the spawned JoinHandle
