### ISSUE TITLE
Erroneous balance for empty accounts.

### ISSUE THREAD

**Issue by cawfree** [a16z/helios#194]
When interacting with the Helios RPC, [`ethers`](https://github.com/ethers-io/ethers.js/) will encounter an error when trying to call `getBalance` on an empty account:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/7922333/218284013-9fb5ea17-868f-491b-96c0-5eda7f4780d2.png">

It seems like `ethers` expected the string value `0x0` opposed to `0x`. For non-empty accounts, the balance is returned successfully.

This was produced against commit [`c7a1bad8e56961316cbd34db3076a8c4735c5756`](https://github.com/a16z/helios/commit/c7a1bad8e56961316cbd34db3076a8c4735c5756).

**Comment by ncitron** [comment]
Thanks for reporting this. Fix is running through CI right now and will be merged in just a few minutes.

**Comment by cawfree** [comment]
@ncitron Legend, thanks so much! I'll bring `react-native-helios` up to this latest fix. Have a good week!
