### ISSUE TITLE
Missing RPC methods

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#200]
Missing RPC methods that might be useful to have.

Feel free to reach out here or on the telegram if you want to discuss how to go about implementing any of these.

- [x] eth_sync
- [x] eth_coinbase
- [ ] eth_feeHistory
- [x] eth_newFilter
- [x] eth_newBlockFilter
- [x] eth_newPendingTransactionFilter
- [x] eth_uninstallFilter
- [x] eth_getFilterChanges
- [ ] eth_getFilterLogs
- [x] eth_getTransactionByBlockHashAndIndex
- [ ] debug_getRawHeader
- [ ] debug_getRawBlock
- [ ] debug_getRawTransaction
- [ ] debug_getRawReceipts
- [ ] debug_getBadBlocks

**Comment by sk1122** [comment]
@ncitron what do you think?

**Comment by sk1122** [comment]
> That's a good point @sk1122. Is it possible to check filter validity ourselves?

No, as they are generated [randomly](https://github.com/ethereum/go-ethereum/blob/master/rpc/subscription.go#L48), there is no way to verify them based on filter data 
 
> I don't think it's a huge deal anyway though, as for the log methods we sort of assume that it is possible for the rpc to withhold logs from us.

Understood, I think we should check it once before handing filter id over to user, what do you think?

Also in future, we can implement DA proofs and Fraud proofs to better secure us against these type of errors?

**Comment by ncitron** [comment]
> Understood, I think we should check it once before handing filter id over to user, what do you think?

How would we check it before handing the id to the user?

**Comment by sk1122** [comment]
we can check if `eth_getFilterChanges` returns an error, if it returns an error meaning that `id` wasn't registered on nodes (execution node can withheld that data though), else means that `id` has been successfully registered and now can be used for tracking changes

**Comment by sk1122** [comment]
but for this, we will need to implement `eth_getFilterChanges`, which returns list of logs if Id is valid, we can just use `eth_getLogs` verification code for verifying this logs

**Comment by sk1122** [comment]
so, should I first open a PR for eth_getFilterChanges?

**Comment by ncitron** [comment]
@sk1122 that would be great!

**Comment by muang0** [comment]
@ncitron I'm interested in contributing one of these methods, any preference which one I should do? Or is there another issue you think would be better suited for a 2nd contrib?

**Comment by ncitron** [comment]
Hey @muang0! A lot of the important ones here have been completed, but if you want to chat about some other contributions we can discuss on Telegram. I'm @ ncitron there.

**Comment by eshaan7** [comment]
I notice that the `eth_getBlockReceipts` RPC method is missing as well. Do we want to add this @ncitron?

**Comment by ncitron** [comment]
I think that would be great @eshaan7

**Comment by eshaan7** [comment]
The following methods are still missing from the `eth_` namespace:

- [ ] `eth_uninstallFilter`
- [ ] `eth_getFilterLogs`
- [ ] `eth_getTransactionByBlockNumberAndIndex` 
- [ ] `eth_createAccessList`
- [ ] `eth_feeHistory`
- [ ] `eth_blobBaseFee`


@ncitron; can you reopen this issue?
