### ISSUE TITLE
helios crashes when running against goerli

### ISSUE THREAD

**Issue by darkryder** [a16z/helios#202]
When I run `/helios -c "http://testing.prater.beacon-api.nimbus.team" -e "https://eth-goerli.g.alchemy.com/v2/<redacted>" -n goerli -w 0xb5c375696913865d7c0e166d87bc7c772b6210dc9edf149f4c7ddc6da0dd4495`, helios panics with

```
[2023-03-06T22:34:16Z INFO  client::rpc] rpc server started at 127.0.0.1:8545
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /users/sambhav/helios/client/src/client.rs:258:80
```

Mainnet works fine: `./helios  -e https://eth-mainnet.g.alchemy.com/v2/XXXX  -w 0x85e6151a246e8fdba36db27a0c7678a575346272fe978c9281e13a8b26cdfa68`

Helios is at 8da632f8f2902a0095bc1fcd6e1a1008950c7002 and compiled using rustc 1.69.0-nightly (5e37043d6 2023-01-22).

Any pointers?

**Comment by ncitron** [comment]
Can you try using a different (and more recent) checkpoint value. Make sure the checkpoint hash is the first Beaconchain block hash in an epoch.

Sometimes the consensus rpc is missing the data for bootstrapping off of a given block which causes this.

I will look into why the error isn't being handled gracefully though.

**Comment by darkryder** [comment]
Using a more recent checkpoint worked -- thanks!
Since this isn't really a bug, shall I close this ticket or do you want to track this here?

**Comment by ncitron** [comment]
Yeah feel free to close
