### ISSUE TITLE
regression for wasm32 target (doesn't compile)

### ISSUE THREAD

**Issue by glihm** [a16z/helios#226]
@ncitron we have a regression in `wasm32` target due to the [commit 1ae57f1b009efd33365d8fdbb61fde13354fa00b](https://github.com/a16z/helios/commit/1ae57f1b009efd33365d8fdbb61fde13354fa00b).

I don't have the rust knowledge to exactly know how to fix that, because the title of the commit
includes "fix". So does this mean the precedent code wasn't working too?

The idea is that, you are excluding `tokio` for `wasm32` target in all configuration files.
So adding a macro to only include this part of the code in targets that are not `wasm32` looks like a solution.

But, what should we implement in the case it's `wasm32`?

You changed

```rust
// previous

let handle = thread::spawn(move || {
    let account_fut = execution.get_account(&address, Some(&slots), &payload);
    block_on(account_fut)
});

handle.join().unwrap()
```

to this:

```rust
// current

let handle = spawn_blocking(move || {
    block_on(execution.get_account(&address, Some(&slots), &payload))
});

block_on(handle)?
```

If the `current` is not valid for `wasm32`, should we insert the `previous` snippet when it's `wasm32` and the `current` in all other cases?

```rust

#[cfg(not(target_arch = "wasm32"))]
fn get_account(&mut self, address: Address, slots: &[H256]) -> Result<Account> {
    let execution = self.execution.clone();
    let payload = self.current_payload.clone();
    let slots = slots.to_owned();

    let handle = spawn_blocking(move || {
        block_on(execution.get_account(&address, Some(&slots), &payload))
    });

    block_on(handle)?
}

#[cfg(target_arch = "wasm32")]
fn get_account(&mut self, address: Address, slots: &[H256]) -> Result<Account> {
    let execution = self.execution.clone();
    let payload = self.current_payload.clone();
    let slots = slots.to_owned();

    let handle = thread::spawn(move || {
        let account_fut = execution.get_account(&address, Some(&slots), &payload);
        block_on(account_fut)
    });

    handle.join().unwrap()
}
```

Once again, I can't evaluate if this is a solution. Any insights welcome and I can contribute with the PR if needed. 👍

**Comment by glihm** [comment]
Using the proposed fix it compiles fine, for `wasm32` and other targets.
We are the implication of such fix? Are there some side effects I am not aware of?

Thanks a lot!

**Comment by ncitron** [comment]
Are you able to perform eth_call in both wasm and regular when you make this change? I originally made the change because eth_call would crash with some weird error (I think due to some dependency weirdness)

**Comment by ncitron** [comment]
wasm support is back up and running in #284
