### ISSUE TITLE
investigate memory leak

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#229]
Got a report of slowly growing mem usage. We should confirm this and track down the source.

**Comment by corvusrabus** [comment]
Hi, I've been looking through the code base to learn more about Ethereum.
If I saw correctly you don't have any unsafe code anywhere so unless one of the crates you're using has a memory leak there shouldn't be one. 

I haven't measured anything but on  the `Node` struct you keep all the `finalized_payloads` in memory, so they grow over time. I don't know how large these are though. Could that be the problem?

**Comment by ncitron** [comment]
Oh that may actually be the issue. Thanks for taking a look.

**Comment by ncitron** [comment]
Recent refactoring should have fixed this.
