### ISSUE TITLE
Getting `could not prove receipt for tx: 0x5bb3…55a8` error

### ISSUE THREAD

**Issue by eranrund** [a16z/helios#250]
I am trying to run the following code on the Goerli test network:
```
    let mut client: Client<FileDB> = ClientBuilder::new()
        .network(Network::GOERLI)
        .data_dir(data_dir)
        .consensus_rpc(consensus_rpc)
        .execution_rpc(&eth_rpc_url)
        .checkpoint("0x7e8d04a93be4eb2fdc7492c544ded2eb1cb36185179d1ab4ea598e1ad7d7793c")
        .build()?;

     let logs = client.get_logs(&Filter::new().select(9452927).event("UpdatedMessages(string,string)")).await.unwrap(); 
````

Surprisingly, it worked yesterday, and today I am getting `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: could not prove receipt for tx: 0x5bb3…55a8`

Any idea what might be causing that?

**Comment by eranrund** [comment]
My guess is that this block is too far in the past and the light client can only look at the most recent 64 blocks (`history_size` in `Node`)

**Comment by ncitron** [comment]
Ah yes it is because we only store the past 64 headers. We should probably handle this case a bit better so that it doesn't panic though.

**Comment by eranrund** [comment]
Thank you. Do you have any suggestions on how one should handle cases where they need to scan the blockchain, but the light client has potentially been down long enough that they missed more than 64 blocks?

**Comment by ncitron** [comment]
If you have a usecase where you are bulk pulling logs, a light client may not be the best fit.

It is difficult to securely get data that is greater than 2 weeks old (read about weak subjectivity if you are interested in why) and even if you could proving logs is pretty inefficient.

If you just need to go a bit deeper in the history though, we can maybe make the history parameter configurable.

**Comment by eranrund** [comment]
Hm, interesting. I will read about that.
My use case does require to look for logs emitted by a specific smart contract. I am interested in doing this inside an SGX enclave. Running a full node is much more challenging in that kind of an environment, so I'm hoping I can get a design to work with the light client. I don't expect to have to deal with more than 2 weeks old data, but I do want to handle a day or two of downtime.

**Comment by ncitron** [comment]
Oh interesting. In that case changing the history length parameter should work for you. I imagine you are forking Helios anyway to get in running in SGX so can just change it directly?

I'd also be interested to hear what you are doing with Helios in SGX. My Telegram is @ ncitron if you want to chat more directly.
