### ISSUE TITLE
error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by ltfschoen** [a16z/helios#259]
Sometimes when I run `cargo run -p helios --example <example_name>` using the code in this PR https://github.com/a16z/helios/pull/253 I get the following error. 
To overcome the error all I have to do is to run the same command again with no other changes, but what is causing me to have to do that?

```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH=" ...
...
/usr/bin/ld: cannot find /opt/target/debug/examples/client-d9f966683b8158f6.4mjdt1mhb4psknyb.rcgu.o: No such file or directory
```

**Comment by ncitron** [comment]
cannot repro and seems intermittent
