### ISSUE TITLE
rpc error on method: spec, message: error decoding response body: expected value at line 1 column 1

### ISSUE THREAD

**Issue by Malak-youness** [a16z/helios#279]
I tried all the steps mentioned. But I keep receiving this error.
command: 
```helios --execution-rpc https://mainnet.infura.io/v3/XXX --data-dir /data --consensus-rpc "https://www.lightclientdata.org" --checkpoint 0xdd93613a1ec95225331d0eea07bd39a5d42dd68e5bc034850f9b0550a00b336f ```

Logs:
```
[2023-10-09T08:09:32Z INFO  client::rpc] rpc server started at 127.0.0.1:8545
[2023-10-09T08:09:33Z ERROR cli] rpc error on method: spec, message: error decoding response body: expected value at line 1 column 1 
```

I have no idea why it's giving me this error although I am using an alchemy execution rpc endpoint.

Any idea how to fix that ?

**Comment by ncitron** [comment]
Oh it looks like we are having some issues with the consensus rpc at lightclientdata.org. I'll get something up and running asap and ping you here when it is resolved.

**Comment by ncitron** [comment]
It should be working now. You may need to use a fresh checkpoint though as this node was synced quite recently. Feel free to reopen if it is not resolved.
