### ISSUE TITLE
Error: out of sync: 1697023721 seconds behind

### ISSUE THREAD

**Issue by ltfschoen** [a16z/helios#282]
i'm using latest 'master' code from this repos commit [fc73eaf](https://github.com/a16z/helios/commit/fc73eafdf86bde0acc25dfb20c560b507cdcd1be).

If I run a script examples/basic.rs (after first commenting out the line `.load_external_fallback()`, and changing it to use Goerli instead of Mainnet environment variables) with `cargo run -p helios --example basic`, then if I add the `log::info!("syncing status: {:#?}", client.syncing().await?);` before the line `let head_block_num = client.get_block_number().await?;`, then when it runs the line `let head_block_num = client.get_block_number().await?;` it outputs the following error.

```bash
[2023-10-11T12:01:19Z INFO  block_addresses] syncing status: IsSyncing(
        SyncProgress {
            current_block: 0,
            highest_block: 6709806,
            starting_block: 0,
            pulled_states: None,
            known_states: None,
            healed_bytecode_bytes: None,
            healed_bytecodes: None,
            healed_trienode_bytes: None,
            healed_trienodes: None,
            healing_bytecode: None,
            healing_trienodes: None,
            synced_account_bytes: None,
            synced_accounts: None,
            synced_bytecode_bytes: None,
            synced_bytecodes: None,
            synced_storage: None,
            synced_storage_bytes: None,
        },
    )

Error: out of sync: 1697025679 seconds behind
```

Why isn't it syncing so I can run further scripts in the command?

I am using environment variable block root checkpoint 0x1470fd9cf3a01d1ebf1d35993c9b9bb05534b1a7f8841109586e674cdf751af3 from latest finalised epoch 209670
associated with its oldest slot 6709440 as previously discussed was the approach to get a checkpoint.

The environment variables I am using are the following

```
GOERLI_CONSENSUS_RPC=http://testing.prater.beacon-api.nimbus.team
GOERLI_EXECUTION_RPC=https://eth-goerli.g.alchemy.com/v2/<MY_API_KEY>
GOERLI_DATA_DIR_EXT=.helios/goerli
GOERLI_CHECKPOINT=0x1470fd9cf3a01d1ebf1d35993c9b9bb05534b1a7f8841109586e674cdf751af3
GOERLI_CHECKPOINT_FALLBACK=https://sync-goerli.beaconcha.in
```

I also tried running the node and waiting for it to sync to the latest block:
```
cargo run -- \
  --network goerli \
  --consensus-rpc http://testing.prater.beacon-api.nimbus.team \
  --execution-rpc https://ethereum-goerli-rpc.allthatnode.com \
  --checkpoint 0x1470fd9cf3a01d1ebf1d35993c9b9bb05534b1a7f8841109586e674cdf751af3 \
  --data-dir $HOME/.helios/data/goerli
```
and then running the script `cargo run -p helios --example basic`, but i get the same error `Error: out of sync: 1697025679 seconds behind`

**Comment by ncitron** [comment]
Oh this brings up an interesting point. In the latest master of helios we have set the sync to function asynchronously. Because of this the `helios.sync()` call does not actually block until helios syncs, so any proceeding calls in the code will throw this error.

We didn't notice it because helios is mostly used via cli where this issue won't crop up.

I think the best solution is to add a `wait_sycned` function to helios which will block until helios syncs.

Thanks for pointing this out.

**Comment by visopsys** [comment]
I also have this error. 

@ncitron  Where should I add the `wait_sycned`?
