### ISSUE TITLE
verifying logs from in between synced blocks

### ISSUE THREAD

**Issue by yuvalelmo** [a16z/helios#342]
Hey everyone,
I am encountering an issue while syncing blocks from `MAINNET`. The blocks transmitted from the consensus layer to the execution’s state do not always follow a consecutive order by block number.

For example, I've added an info log at the point where the execution's state receives the execution payloads from the consensus, to understand which block are getting cached in the state.
Here's an illustrative screenshot:
![Screenshot 2024-07-30 at 17 54 07](https://github.com/user-attachments/assets/9b850cc9-0aaa-4527-b1d3-5aa607a0dac0)

In the picture we can see that block `20420065` is successfully synced to the execution state, and then the subsequent block is `20420067`, and no syncing of `20420066`.
The same goes for `20420069`, `20420071` - not synced.

My questions is, what should I do if I need to use `get_logs` to retrieve and verify logs from one of these missing blocks? In the code, for verifying logs, it queries the entire block from the state to accomplish this - however, the block appears to be missing.
For example, if I have a log I wish to query from block `20420069`, is it possible to verify this log?

**Comment by ncitron** [comment]
Ah this is a good catch. We should be backfilling blocks if we miss one, but as it stands right now we do not.

For the case of log fetching it will miss that log, which is definitely a bug. We'll get on this soon.

**Comment by yuvalelmo** [comment]
Just out of curiosity, how would you backfill the missing blocks?
Since the blocks that are received from `consensus` are the execution payloads of the beacon headers we get from the updates, which are not controllable in terms of which beacon block header would you get inside the `Update`, how would you be able to backfill this gap?
If I'm not clear, what i mean is that whenever you fetch an `Update`, you can only give it a "from" period, but you cannot limit it with a slot number or anything else, so how can you fetch the exact beacon block that would fit to the missing execution block?

**Comment by ncitron** [comment]
So an easy way to do this if we have the latest block (let's call this block n) but are missing the prior block n-1, then we can fetch the previous blockhash pointer from block n, ask the rpc for block n-1, hash it, and confirm that it matches the pointer from block n.

**Comment by ncitron** [comment]
Block backfill is not implemented and available in 0.7.0.

Fixed in #391
