### ISSUE TITLE
sync failed err=invalid sync committee period

### ISSUE THREAD

**Issue by 841660202** [a16z/helios#361]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/80e60dbc-7e2d-4aa2-af0a-fd8cc87243e8">

```

helios --data-dir ~/helios_data --rpc-bind-ip 127.0.0.1 --rpc-port 8545 --execution-rpc https://eth-mainnet.g.alchemy.com/v2/OGS9J9Eb--3A9eJscGViBZ4SOc6A3WO5

```

**Comment by ncitron** [comment]
Try running with the `-l` flag which will fetch you a more recent checkpoint block to sync off of. You will only need to use this flag once, then future syncs should work fine. Let me know if you run into any other issues.
