### ISSUE TITLE
Support risc-v

### ISSUE THREAD

**Issue by come-maiz** [a16z/helios#370]
RISC-V is a good start to get Ethereum nodes running in free hardware, which is a necessary step for a local-first decentralized economy. Lightclients are another necessary step, so these two worlds together are very powerful.

Please support the risc-v architecture in this project.

**Comment by come-maiz** [comment]
helios fails to compile in risc-v because it has an old version of [ring](https://github.com/briansmith/ring/).

We need to update [jsonrpsee](https://github.com/paritytech/jsonrpsee) in this repository in order to update ring.

**Comment by ncitron** [comment]
closed by #374
