### ISSUE TITLE
feat: support pulling opstack system config for ethereum light client

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#408]
Right now Helios's OP Stack only uses hard codes sequencer unsafe signer keys. This is fine, but they can in theory change, so it would be nice to be able to fetch them from the L1 light client using the OP Stack's `SystemConfig` contract.

I'd like to avoid having a requirement of the full Ethereum execution RPC, so think it would be best just to use Ethereum's consensus backend and throw together a special endpoint on the opstack consensus server for providing the single merkle proof we need and verifying it against the most recent header fetched from the Ethereum consensus.

**Comment by 0xRampey** [comment]
I can take this up. 
Just want to make sure this is the flow we want:
`helios opstack ....` -> Spin up Eth consensus client-> Fetch proof and verify signer key -> Shutdown eth consensus client -> Spin up op consensus client

**Comment by ncitron** [comment]
Basically yes.

One thing we should also do to decrease latency is start the opstack client eagerly with the hardcoded key and update it with the actual key if needed.
