### ISSUE TITLE
fix: tests failing in `helios-ethereum`

### ISSUE THREAD

**Issue by 0xRampey** [a16z/helios#415]
Unit tests for `ConsensusClient` expect more generic arguments

**Comment by mw2000** [comment]
I see a few more compiler errors in the `benches` package while using rust-analyzer. Putting up a PR to fix those + tests

**Comment by 0xRampey** [comment]
I have an (almost) ready PR for the tests. 
Perhaps you can take on just the 'benches' crate to prevent duplication?

**Comment by 0xRampey** [comment]
No worries. I should've marked the issue before starting work on it. Thanks!
