### ISSUE TITLE
chore: rename optimism to op-mainnet

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#421]
Optimism has been renamed to OP Mainnet. We should change all references to `optimism` to `op-mainnet` to reflect this.

**Comment by MuhtasimTanmoy** [comment]
Which occurrence of `optimism` is within the scope of of renaming?

- No endpoints are affected right?

```
README.md

[op-mainnet]
consensus_rpc = "https://optimism.operationsolarstorm.org"
execution_rpc = "https://opt-mainnet.g.alchemy.com/v2/XXXXX"
```

```
opstack/src/server/net/block_handler.rs

blocks_v3_topic: IdentTopic::new(format!("/optimism/{}/2/blocks", chain_id)) 
```

- Does `DOM` elements id has any other reference? or should be renamed?
```
helios-ts/index.html

<div class="panel" id="optimism-panel">
....
<div class="blocks" id="optimism-blocks">
...
<pre class="block-info syncing" id="optimism-syncing">Syncing...</pre>
```

Other than that, does https://github.com/a16z/helios/pull/422 looks sufficient?
