### ISSUE TITLE
[bug] Incorrect filter method names

### ISSUE THREAD

**Issue by eshaan7** [a16z/helios#443]
The following 3 method names are incorrect:
![image](https://github.com/user-attachments/assets/60fbd85b-9780-46d4-83b3-74ed5e5e11a4)

As per the [spec](https://ethereum.github.io/execution-apis/api-documentation/), these should be `eth_newFilter`, `eth_newBlockFilter` and `eth_newPendingTransactionFilter` respectively:

<img width="1214" alt="image" src="https://github.com/user-attachments/assets/c832f44c-3741-4eea-9260-f209a31abaca">

<br>
<br>

Also, these 3 methods seem to be missing corresponding Wasm bindings. Is that intended?

**Comment by ncitron** [comment]
Ah good catch. We should change this and make sure the names in the Client/Node objects are also made to align with the jsonrpc names for consistency. And yes lets add these methods to the wasm binding as well.

**Comment by eshaan7** [comment]
Will be raising a separate PR for the Wasm bindings because that is missing for few other methods beyond these 3. Tracking in https://github.com/a16z/helios/issues/451.
