### ISSUE TITLE
installer updated?

### ISSUE THREAD

**Issue by gigamesh** [a16z/helios#456]
Just a heads up, I installed using `curl https://raw.githubusercontent.com/a16z/helios/master/heliosup/install | bash` but couldn't connect to `op-mainnet` as described in the readme. Then I noticed it used to be called `optimism`, which worked.

**Comment by ncitron** [comment]
Ah good catch. We changed the naming recently an have not pushed an update to the installer. Our next release is coming soon and will resolve.
